### Private targets
# Targets prefixed with `_` are "private": they exist only as prerequisites of public
# targets (e.g. `lint: _prelint`) and are not meant to be run directly.
# MAKECMDGOALS holds only the goals typed on the command line, so prerequisites are unaffected.
PRIVATE_GOALS := $(filter _%,$(MAKECMDGOALS))
ifneq ($(PRIVATE_GOALS),)
$(error Cannot run private target(s) directly: $(PRIVATE_GOALS). Targets starting with "_" are internal helpers used by other targets. Run `make help` to see the public targets)
endif

### Utilities
.PHONY: all help clean quality ready

all: help

help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Utilities:"
	@echo "  help              Show this help message"
	@echo "  clean             Cleanup nuxt caches"
	@echo "  ready             Deployment pre-checks"
	@echo ""
	@echo "Quality:"
	@echo "  quality           Run all quality checks"
	@echo ""
	@echo "  lint              Run all linters"
	@echo "  lint-prettier     Run Prettier check only"
	@echo "  lint-eslint       Run ESLint only"
	@echo ""
	@echo "  format            Run all formatters"
	@echo "  format-prettier   Auto-fix Prettier only"
	@echo "  format-eslint     Auto-fix ESLint only"
	@echo ""
	@echo "Testing:"
	@echo "  test              Run all tests"
	@echo "  test-unit         Run unit and component tests (Vitest)"
	@echo "  test-e2e          Run system tests (Playwright)"

clean:
	npx nuxi cleanup

quality: format lint test

ready: quality
	@if [ -n "$$(git status --porcelain)" ]; then \
		echo "Error: working tree is dirty"; \
		git status --short; \
		exit 1; \
	fi

### Quality
.PHONY: _prelint lint lint-eslint lint-prettier format format-prettier format-eslint

# eslint.config.mjs imports the config generated by `nuxt prepare` (removed by `make clean`)
_prelint: .nuxt/eslint.config.mjs

.nuxt/eslint.config.mjs:
	npx nuxt prepare

lint: _prelint
	npm run lint

lint-prettier:
	npm run lint:prettier

lint-eslint: _prelint
	npm run lint:eslint

format: _prelint
	npm run format

format-prettier:
	npm run format:prettier

format-eslint: _prelint
	npm run format:eslint

### Testing
.PHONY: test test-unit test-e2e

test:
	npm run test

test-unit:
	npm run test:unit

test-e2e:
	npm run test:e2e
